#Explore.R
library(ggplot2)
library(GGally)

my_fn <- function(data, mapping, ...){
    p <- ggplot(data = data, mapping = mapping) + 
        geom_point() + 
        geom_smooth(method=loess, fill="red", color="red", ...) +
        geom_smooth(method=lm, fill="blue", color="blue", ...)
    p
}

g = ggpairs(train2,columns = 1:4, lower = list(continuous = my_fn))
g

plot(train2$X)
plot(train2$user_name)
plot(train2$raw_timestamp_part_1)
plot(train2$raw_timestamp_part_2)
plot(train2$cvtd_timestamp)
plot(train2$new_window)
plot(train2$num_window)
plot(train2$roll_belt)
plot(train2$pitch_belt)
plot(train2$yaw_belt)
plot(train2$total_accel_belt)
plot(train2$gyros_belt_x)
plot(train2$gyros_belt_y)
plot(train2$gyros_belt_z)
plot(train2$accel_belt_x)
plot(train2$accel_belt_y)
plot(train2$accel_belt_z)
plot(train2$magnet_belt_x)
plot(train2$magnet_belt_y)
plot(train2$magnet_belt_z)
plot(train2$roll_arm)
plot(train2$pitch_arm)
plot(train2$yaw_arm)
plot(train2$total_accel_arm)
plot(train2$gyros_arm_x)
plot(train2$gyros_arm_y)
plot(train2$gyros_arm_z)
plot(train2$accel_arm_x)
plot(train2$accel_arm_y)
plot(train2$accel_arm_z)
plot(train2$magnet_arm_x)
plot(train2$magnet_arm_y)
plot(train2$magnet_arm_z)
plot(train2$roll_dumbbell)
plot(train2$pitch_dumbbell)
plot(train2$yaw_dumbbell)
plot(train2$total_accel_dumbbell)
plot(train2$gyros_dumbbell_x)
plot(train2$gyros_dumbbell_y)
plot(train2$gyros_dumbbell_z)
plot(train2$accel_dumbbell_x)
plot(train2$accel_dumbbell_y)
plot(train2$accel_dumbbell_z)
plot(train2$magnet_dumbbell_x)
plot(train2$magnet_dumbbell_y)
plot(train2$magnet_dumbbell_z)
plot(train2$roll_forearm)
plot(train2$pitch_forearm)
plot(train2$yaw_forearm)
plot(train2$total_accel_forearm)
plot(train2$gyros_forearm_x)
plot(train2$gyros_forearm_y)
plot(train2$gyros_forearm_z)
plot(train2$accel_forearm_x)
plot(train2$accel_forearm_y)
plot(train2$accel_forearm_z)
plot(train2$magnet_forearm_x)
plot(train2$magnet_forearm_y)
plot(train2$magnet_forearm_z)
plot(train2$classe)


with(train2, plot(X, col=classe))
with(train2, plot(user_name, col=classe))
with(train2, plot(raw_timestamp_part_1, col=classe))
with(train2, plot(raw_timestamp_part_2, col=classe))
with(train2, plot(cvtd_timestamp, col=classe))
with(train2, plot(new_window, col=classe))
with(train2, plot(num_window, col=classe))
with(train2, plot(roll_belt, col=classe))
with(train2, plot(pitch_belt, col=classe))
with(train2, plot(yaw_belt, col=classe))
with(train2, plot(total_accel_belt, col=classe))
with(train2, plot(gyros_belt_x, col=classe))
with(train2, plot(gyros_belt_y, col=classe))
with(train2, plot(gyros_belt_z, col=classe))
with(train2, plot(accel_belt_x, col=classe))
with(train2, plot(accel_belt_y, col=classe))
with(train2, plot(accel_belt_z, col=classe))
with(train2, plot(magnet_belt_x, col=classe))
with(train2, plot(magnet_belt_y, col=classe))
with(train2, plot(magnet_belt_z, col=classe))
with(train2, plot(roll_arm, col=classe))
with(train2, plot(pitch_arm, col=classe))
with(train2, plot(yaw_arm, col=classe))
with(train2, plot(total_accel_arm, col=classe))
with(train2, plot(gyros_arm_x, col=classe))
with(train2, plot(gyros_arm_y, col=classe))
with(train2, plot(gyros_arm_z, col=classe))
with(train2, plot(accel_arm_x, col=classe))
with(train2, plot(accel_arm_y, col=classe))
with(train2, plot(accel_arm_z, col=classe))
with(train2, plot(magnet_arm_x, col=classe))
with(train2, plot(magnet_arm_y, col=classe))
with(train2, plot(magnet_arm_z, col=classe))
with(train2, plot(roll_dumbbell, col=classe))
with(train2, plot(pitch_dumbbell, col=classe))
with(train2, plot(yaw_dumbbell, col=classe))
with(train2, plot(total_accel_dumbbell, col=classe))
with(train2, plot(gyros_dumbbell_x, col=classe))
with(train2, plot(gyros_dumbbell_y, col=classe))
with(train2, plot(gyros_dumbbell_z, col=classe))
with(train2, plot(accel_dumbbell_x, col=classe))
with(train2, plot(accel_dumbbell_y, col=classe))
with(train2, plot(accel_dumbbell_z, col=classe))
with(train2, plot(magnet_dumbbell_x, col=classe))
with(train2, plot(magnet_dumbbell_y, col=classe))
with(train2, plot(magnet_dumbbell_z, col=classe))
with(train2, plot(roll_forearm, col=classe))
with(train2, plot(pitch_forearm, col=classe))
with(train2, plot(yaw_forearm, col=classe))
with(train2, plot(total_accel_forearm, col=classe))
with(train2, plot(gyros_forearm_x, col=classe))
with(train2, plot(gyros_forearm_y, col=classe))
with(train2, plot(gyros_forearm_z, col=classe))
with(train2, plot(accel_forearm_x, col=classe))
with(train2, plot(accel_forearm_y, col=classe))
with(train2, plot(accel_forearm_z, col=classe))
with(train2, plot(magnet_forearm_x, col=classe))
with(train2, plot(magnet_forearm_y, col=classe))
with(train2, plot(magnet_forearm_z, col=classe))
with(train2, plot(classe, col=classe))

with(train2, plot(X, user_name, col=classe))
with(train2, plot(user_name, user_name, col=classe))
with(train2, plot(raw_timestamp_part_1, user_name, col=classe))
with(train2, plot(raw_timestamp_part_2, user_name, col=classe))
with(train2, plot(cvtd_timestamp, user_name, col=classe))
with(train2, plot(new_window, user_name, col=classe))
with(train2, plot(num_window, user_name, col=classe))
with(train2, plot(roll_belt, user_name, col=classe))
with(train2, plot(pitch_belt, user_name, col=classe))
with(train2, plot(yaw_belt, user_name, col=classe))
with(train2, plot(total_accel_belt, user_name, col=classe))
with(train2, plot(gyros_belt_x, user_name, col=classe))
with(train2, plot(gyros_belt_y, user_name, col=classe))
with(train2, plot(gyros_belt_z, user_name, col=classe))
with(train2, plot(accel_belt_x, user_name, col=classe))
with(train2, plot(accel_belt_y, user_name, col=classe))
with(train2, plot(accel_belt_z, user_name, col=classe))
with(train2, plot(magnet_belt_x, user_name, col=classe))
with(train2, plot(magnet_belt_y, user_name, col=classe))
with(train2, plot(magnet_belt_z, user_name, col=classe))
with(train2, plot(roll_arm, user_name, col=classe))
with(train2, plot(pitch_arm, user_name, col=classe))
with(train2, plot(yaw_arm, user_name, col=classe))
with(train2, plot(total_accel_arm, user_name, col=classe))
with(train2, plot(gyros_arm_x, user_name, col=classe))
with(train2, plot(gyros_arm_y, user_name, col=classe))
with(train2, plot(gyros_arm_z, user_name, col=classe))
with(train2, plot(accel_arm_x, user_name, col=classe))
with(train2, plot(accel_arm_y, user_name, col=classe))
with(train2, plot(accel_arm_z, user_name, col=classe))
with(train2, plot(magnet_arm_x, user_name, col=classe))
with(train2, plot(magnet_arm_y, user_name, col=classe))
with(train2, plot(magnet_arm_z, user_name, col=classe))
with(train2, plot(roll_dumbbell, user_name, col=classe))
with(train2, plot(pitch_dumbbell, user_name, col=classe))
with(train2, plot(yaw_dumbbell, user_name, col=classe))
with(train2, plot(total_accel_dumbbell, user_name, col=classe))
with(train2, plot(gyros_dumbbell_x, user_name, col=classe))
with(train2, plot(gyros_dumbbell_y, user_name, col=classe))
with(train2, plot(gyros_dumbbell_z, user_name, col=classe))
with(train2, plot(accel_dumbbell_x, user_name, col=classe))
with(train2, plot(accel_dumbbell_y, user_name, col=classe))
with(train2, plot(accel_dumbbell_z, user_name, col=classe))
with(train2, plot(magnet_dumbbell_x, user_name, col=classe))
with(train2, plot(magnet_dumbbell_y, user_name, col=classe))
with(train2, plot(magnet_dumbbell_z, user_name, col=classe))
with(train2, plot(roll_forearm, user_name, col=classe))
with(train2, plot(pitch_forearm, user_name, col=classe))
with(train2, plot(yaw_forearm, user_name, col=classe))
with(train2, plot(total_accel_forearm, user_name, col=classe))
with(train2, plot(gyros_forearm_x, user_name, col=classe))
with(train2, plot(gyros_forearm_y, user_name, col=classe))
with(train2, plot(gyros_forearm_z, user_name, col=classe))
with(train2, plot(accel_forearm_x, user_name, col=classe))
with(train2, plot(accel_forearm_y, user_name, col=classe))
with(train2, plot(accel_forearm_z, user_name, col=classe))
with(train2, plot(magnet_forearm_x, user_name, col=classe))
with(train2, plot(magnet_forearm_y, user_name, col=classe))
with(train2, plot(magnet_forearm_z, user_name, col=classe))
with(train2, plot(classe, user_name, col=classe))

