#Load data

library(lubridate)
library(plyr)
library(dplyr)

# ".\\data\\pml-training.csv"
# ".\\data\\pml-testing.csv"

trainClasses <- c("integer",
                  "factor",
                  "integer",
                  "integer",
                  "character",
                  
                  )
train <- read.csv(".\\data\\pml-training.csv",
                  na.strings = c("NA", "#DIV/0!")
                  )
str(train)
names(train)

lapply(train, class)


ddply(train, names(train), class)
adply(train, 2, class)

#convert the time into correct format
train$cvtd_timestamp <- dmy_hm(train$cvtd_timestamp)

sum(is.na(train$min_pitch_belt))

nmissing <- function(x) {
    sum(is.na(x))
}
isnaTrain <- colwise(nmissing)(train)


aboutTrain <- data.frame(names(train))
aboutTrain <- cbind(aboutTrain, No_of_na = unname(t(isnaTrain)))
write.csv(aboutTrain, file = ".\\data\\aboutTrain.csv")

sapply(train, min)

arrange(aboutTrain, No_of_na)

#keep columns with less than 19000 nas
train2 <- select(train, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 37, 38, 39, 40, 41, 
                 42, 43, 44, 45, 46, 47, 48, 49, 60, 61, 62, 63, 64, 65, 66, 67, 
                 68, 84, 85, 86, 102, 113, 114, 115, 116, 117, 118, 119, 120, 
                 121, 122, 123, 124, 140, 151, 152, 153, 154, 155, 156, 157, 
                 158, 159, 160)
filter(aboutTrain, No_of_na < 19000)
colsTrain <- c(select(filter(aboutTrain, No_of_na < 19000), names.train.))
train3 <- subset(train,
    subset = c(select(filter(aboutTrain, No_of_na < 19000), names.train.))
)
match(names(train), colsTrain)
train %>%
    select(colsTrain)

table(train$user_name, useNA = "ifany")
table(train$raw_timestamp_part_1, useNA = "ifany")
table(train$raw_timestamp_part_2, useNA = "ifany")
table(train$cvtd_timestamp, useNA = "ifany")
table(train$new_window, useNA = "ifany")
table(train$num_window, useNA = "ifany")
table(train$roll_belt, useNA = "ifany")
table(train$pitch_belt, useNA = "ifany")
table(train$yaw_belt, useNA = "ifany")
table(train$total_accel_belt, useNA = "ifany")
table(train$kurtosis_roll_belt, useNA = "ifany")
table(train$kurtosis_picth_belt, useNA = "ifany")
table(train$kurtosis_yaw_belt, useNA = "ifany")
table(train$skewness_roll_belt, useNA = "ifany")
table(train$skewness_roll_belt.1, useNA = "ifany")
table(train$skewness_yaw_belt, useNA = "ifany")
table(train$max_roll_belt, useNA = "ifany")
table(train$max_picth_belt, useNA = "ifany")
table(train$max_yaw_belt, useNA = "ifany")
table(train$min_roll_belt, useNA = "ifany")
table(train$min_pitch_belt, useNA = "ifany")
table(train$min_yaw_belt, useNA = "ifany")
table(train$amplitude_roll_belt, useNA = "ifany")
table(train$amplitude_pitch_belt, useNA = "ifany")
table(train$amplitude_yaw_belt, useNA = "ifany")
table(train$var_total_accel_belt, useNA = "ifany")
table(train$avg_roll_belt, useNA = "ifany")
table(train$stddev_roll_belt, useNA = "ifany")
table(train$var_roll_belt, useNA = "ifany")
table(train$avg_pitch_belt, useNA = "ifany")
table(train$stddev_pitch_belt, useNA = "ifany")
table(train$var_pitch_belt, useNA = "ifany")
table(train$avg_yaw_belt, useNA = "ifany")
table(train$stddev_yaw_belt, useNA = "ifany")
table(train$var_yaw_belt, useNA = "ifany")
table(train$gyros_belt_x, useNA = "ifany")
table(train$gyros_belt_y, useNA = "ifany")
table(train$gyros_belt_z, useNA = "ifany")
table(train$accel_belt_x, useNA = "ifany")
table(train$accel_belt_y, useNA = "ifany")
table(train$accel_belt_z, useNA = "ifany")
table(train$magnet_belt_x, useNA = "ifany")
table(train$magnet_belt_y, useNA = "ifany")
table(train$magnet_belt_z, useNA = "ifany")
table(train$roll_arm, useNA = "ifany")
table(train$pitch_arm, useNA = "ifany")
table(train$yaw_arm, useNA = "ifany")
table(train$total_accel_arm, useNA = "ifany")
table(train$var_accel_arm, useNA = "ifany")
table(train$avg_roll_arm, useNA = "ifany")
table(train$stddev_roll_arm, useNA = "ifany")
table(train$var_roll_arm, useNA = "ifany")
table(train$avg_pitch_arm, useNA = "ifany")
table(train$stddev_pitch_arm, useNA = "ifany")
table(train$var_pitch_arm, useNA = "ifany")
table(train$avg_yaw_arm, useNA = "ifany")
table(train$stddev_yaw_arm, useNA = "ifany")
table(train$var_yaw_arm, useNA = "ifany")
table(train$gyros_arm_x, useNA = "ifany")
table(train$gyros_arm_y, useNA = "ifany")
table(train$gyros_arm_z, useNA = "ifany")
table(train$accel_arm_x, useNA = "ifany")
table(train$accel_arm_y, useNA = "ifany")
table(train$accel_arm_z, useNA = "ifany")
table(train$magnet_arm_x, useNA = "ifany")
table(train$magnet_arm_y, useNA = "ifany")
table(train$magnet_arm_z, useNA = "ifany")
table(train$kurtosis_roll_arm, useNA = "ifany")
table(train$kurtosis_picth_arm, useNA = "ifany")
table(train$kurtosis_yaw_arm, useNA = "ifany")
table(train$skewness_roll_arm, useNA = "ifany")
table(train$skewness_pitch_arm, useNA = "ifany")
table(train$skewness_yaw_arm, useNA = "ifany")
table(train$max_roll_arm, useNA = "ifany")
table(train$max_picth_arm, useNA = "ifany")
table(train$max_yaw_arm, useNA = "ifany")
table(train$min_roll_arm, useNA = "ifany")
table(train$min_pitch_arm, useNA = "ifany")
table(train$min_yaw_arm, useNA = "ifany")
table(train$amplitude_roll_arm, useNA = "ifany")
table(train$amplitude_pitch_arm, useNA = "ifany")
table(train$amplitude_yaw_arm, useNA = "ifany")
table(train$roll_dumbbell, useNA = "ifany")
table(train$pitch_dumbbell, useNA = "ifany")
table(train$yaw_dumbbell, useNA = "ifany")
table(train$kurtosis_roll_dumbbell, useNA = "ifany")
table(train$kurtosis_picth_dumbbell, useNA = "ifany")
table(train$kurtosis_yaw_dumbbell, useNA = "ifany")
table(train$skewness_roll_dumbbell, useNA = "ifany")
table(train$skewness_pitch_dumbbell, useNA = "ifany")
table(train$skewness_yaw_dumbbell, useNA = "ifany")
table(train$max_roll_dumbbell, useNA = "ifany")
table(train$max_picth_dumbbell, useNA = "ifany")
table(train$max_yaw_dumbbell, useNA = "ifany")
table(train$min_roll_dumbbell, useNA = "ifany")
table(train$min_pitch_dumbbell, useNA = "ifany")
table(train$min_yaw_dumbbell, useNA = "ifany")
table(train$amplitude_roll_dumbbell, useNA = "ifany")
table(train$amplitude_pitch_dumbbell, useNA = "ifany")
table(train$amplitude_yaw_dumbbell, useNA = "ifany")
table(train$total_accel_dumbbell, useNA = "ifany")
table(train$var_accel_dumbbell, useNA = "ifany")
table(train$avg_roll_dumbbell, useNA = "ifany")
table(train$stddev_roll_dumbbell, useNA = "ifany")
table(train$var_roll_dumbbell, useNA = "ifany")
table(train$avg_pitch_dumbbell, useNA = "ifany")
table(train$stddev_pitch_dumbbell, useNA = "ifany")
table(train$var_pitch_dumbbell, useNA = "ifany")
table(train$avg_yaw_dumbbell, useNA = "ifany")
table(train$stddev_yaw_dumbbell, useNA = "ifany")
table(train$var_yaw_dumbbell, useNA = "ifany")
table(train$gyros_dumbbell_x, useNA = "ifany")
table(train$gyros_dumbbell_y, useNA = "ifany")
table(train$gyros_dumbbell_z, useNA = "ifany")
table(train$accel_dumbbell_x, useNA = "ifany")
table(train$accel_dumbbell_y, useNA = "ifany")
table(train$accel_dumbbell_z, useNA = "ifany")
table(train$magnet_dumbbell_x, useNA = "ifany")
table(train$magnet_dumbbell_y, useNA = "ifany")
table(train$magnet_dumbbell_z, useNA = "ifany")
table(train$roll_forearm, useNA = "ifany")
table(train$pitch_forearm, useNA = "ifany")
table(train$yaw_forearm, useNA = "ifany")
table(train$kurtosis_roll_forearm, useNA = "ifany")
table(train$kurtosis_picth_forearm, useNA = "ifany")
table(train$kurtosis_yaw_forearm, useNA = "ifany")
table(train$skewness_roll_forearm, useNA = "ifany")
table(train$skewness_pitch_forearm, useNA = "ifany")
table(train$skewness_yaw_forearm, useNA = "ifany")
table(train$max_roll_forearm, useNA = "ifany")
table(train$max_picth_forearm, useNA = "ifany")
table(train$max_yaw_forearm, useNA = "ifany")
table(train$min_roll_forearm, useNA = "ifany")
table(train$min_pitch_forearm, useNA = "ifany")
table(train$min_yaw_forearm, useNA = "ifany")
table(train$amplitude_roll_forearm, useNA = "ifany")
table(train$amplitude_pitch_forearm, useNA = "ifany")
table(train$amplitude_yaw_forearm, useNA = "ifany")
table(train$total_accel_forearm, useNA = "ifany")
table(train$var_accel_forearm, useNA = "ifany")
table(train$avg_roll_forearm, useNA = "ifany")
table(train$stddev_roll_forearm, useNA = "ifany")
table(train$var_roll_forearm, useNA = "ifany")
table(train$avg_pitch_forearm, useNA = "ifany")
table(train$stddev_pitch_forearm, useNA = "ifany")
table(train$var_pitch_forearm, useNA = "ifany")
table(train$avg_yaw_forearm, useNA = "ifany")
table(train$stddev_yaw_forearm, useNA = "ifany")
table(train$var_yaw_forearm, useNA = "ifany")
table(train$gyros_forearm_x, useNA = "ifany")
table(train$gyros_forearm_y, useNA = "ifany")
table(train$gyros_forearm_z, useNA = "ifany")
table(train$accel_forearm_x, useNA = "ifany")
table(train$accel_forearm_y, useNA = "ifany")
table(train$accel_forearm_z, useNA = "ifany")
table(train$magnet_forearm_x, useNA = "ifany")
table(train$magnet_forearm_y, useNA = "ifany")
table(train$magnet_forearm_z, useNA = "ifany")
table(train$classe, useNA = "ifany")

